# Generated by Django 4.2 on 2026-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_courier_name_sale_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('delivery_days', models.CharField(default='2-5 business days', max_length=100)),
                ('courier_partners', models.CharField(blank=True, default='DHL, FedEx, UPS', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Setting',
                'verbose_name_plural': 'Delivery Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_order_alerts', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('delivery_updates', models.BooleanField(default=False)),
                ('daily_sales_report', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_enabled', models.BooleanField(default=True)),
                ('card_enabled', models.BooleanField(default=True)),
                ('mobile_money_enabled', models.BooleanField(default=False)),
                ('crypto_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout', models.IntegerField(default=60, help_text='Minutes')),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('password_min_length', models.BooleanField(default=True)),
                ('password_case_required', models.BooleanField(default=True)),
                ('password_special_chars', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Setting',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default="Vera's Choice", max_length=200)),
                ('store_tagline', models.CharField(blank=True, default='Royal Boutique POS System', max_length=500)),
                ('store_address', models.TextField(blank=True, default='123 Royal Street, Boutique District, City')),
                ('store_phone', models.CharField(blank=True, default='+1 234 567 8900', max_length=20)),
                ('store_email', models.EmailField(blank=True, default='info@veraschoice.com', max_length=254)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('INR', 'INR (₹)')], default='USD', max_length=10)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=20)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('EST', 'EST'), ('PST', 'PST'), ('GMT', 'GMT')], default='GMT', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('default_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_rules', models.TextField(blank=True, default='• 10% off on orders above $100\n• Loyalty points redemption\n• Seasonal promotions\n• First-time customer discount: 15%')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Setting',
                'verbose_name_plural': 'Tax Settings',
            },
        ),
    ]
