"""
Django settings for pos project.
Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=gf*2)8a*04*ah*e%)m%5)5%+_!&9wjwmnc2*&3!ztq%g6x&f='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to True for development

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'core.context_processors.store_settings',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pos.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400

# CSRF settings
CSRF_TRUSTED_ORIGINS = ['https://*.pythonanywhere.com', 'http://localhost:8000', 'http://127.0.0.1:8000']
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False

# ==========================================
# JAZZMIN SETTINGS - ROYAL THEME
# ==========================================

JAZZMIN_SETTINGS = {
    # Site branding - Royal Theme
    "site_title": " Vera's Choice - Royal POS",
    "site_header": " Vera's Choice",
    "site_brand": " Vera's Choice",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": " Welcome to Vera's Choice  POS Admin",
    "copyright": "🌸 Vera's Choice ",
    
    # Navigation menu customization
    "show_ui_builder": True,
    
    # Menu customization - Royal themed
    "topmenu_links": [
        {"name": "Dashboard", "url": "/", "permissions": ["auth.view_user"]},
        {"name": " POS", "url": "/pos/", "permissions": ["auth.view_user"]},
        {"app": "core"},
        {"name": " Support", "url": "https://github.com", "new_window": True},
    ],
    
    # Custom menu items
    "custom_links": {
        "core": [{
            "name": " Dashboard",
            "url": "/",
            "icon": "fas fa-crown",
            "permissions": ["auth.view_user"]
        }]
    },
    
    # UI Customization
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible", 
        "auth.group": "vertical_tabs"
    },
    
    # Icons - Royal themed
    "icons": {
        "auth": "fas fa-users-crown",
        "auth.user": "fas fa-user-crown",
        "auth.Group": "fas fa-users",
        "core.Category": "fas fa-tags",
        "core.Product": "fas fa-gem",
        "core.Customer": "fas fa-user-tie",
        "core.Supplier": "fas fa-truck",
        "core.Sale": "fas fa-shopping-cart",
        "core.SaleItem": "fas fa-cart-plus",
        "core.InventoryMovement": "fas fa-warehouse",
    },
    
    # Default icons
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Related modal
    "related_modal_active": True,
    
    # UI Themes
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Hide apps from menu
    "hide_apps": [],
    
    # Language settings
    "language_chooser": False,
}

# ==========================================
# JAZZMIN UI TWEAKS - ROYAL LAVENDER THEME
# ==========================================

JAZZMIN_UI_TWEAKS = {
    # Navbar
    "navbar_small_text": False,
    "navbar_fixed": True,
    
    # Footer
    "footer_small_text": False,
    "footer_fixed": False,
    
    # Body
    "body_small_text": False,
    
    # Brand
    "brand_small_text": False,
    "brand_colour": "navbar-purple",  # Royal purple
    
    # Accent color - Lavender
    "accent": "accent-lavender",
    
    # Navbar theme - Royal Lavender
    "navbar": "navbar-dark navbar-purple",
    "no_navbar_border": False,
    
    # Layout
    "layout_boxed": False,
    
    # Sidebar - Royal Lavender
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-purple",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    # Theme
    "theme": "default",
    "dark_mode_theme": None,
    
    # Buttons - Royal style
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    
    # Actions
    "actions_sticky_top": False
}

# ==========================================
# CUSTOM ADMIN HEADER - ROYAL THEME
# ==========================================

# Add custom CSS for Royal theme
JAZZMIN_SETTINGS["custom_css"] = None

# You can add a custom CSS file by creating static/css/jazzmin-custom.css
# and uncommenting the line below:
# JAZZMIN_SETTINGS["custom_css"] = "css/jazzmin-custom.css"

# ==========================================
# LOGGING (Optional)
# ==========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
